pipeline {
    parameters {
        string(defaultValue: 'Hello', name: 'ECHO_TEXT')
    }
    agent { label 'PC-Monitoring' }
    stages {
        stage('Main') {
            steps {
                echo "ECHO_TEXT from PRODUCTION DIRECTORY is: ${params.ECHO_TEXT}"
            }
        }
    }
}
